### PR TITLE
Call DSI commands from a docker container instead of a DSI installation

### PR DESCRIPTION
**Pull request by orsinije**
Ability to deploy a DSI solution from a Docker container. It avoids the need to do the deployment
from a DSI installation.

### CODE REVIEW

**Comment by orsinije** [comment]
Corresponding  issue: #69

**Comment by remibm** [comment]
Looks fine to me.

**Comment by remibm** [comment]
this doesnt seem to work on macos:
we probably need an improved way to deal with JAVA_HOME in server.env that works on dsi-runtime-openjdk and dsi-runtime-ibmjava base images too (which both come with their own JAVA_HOME), like in start.sh.

**Comment by orsinije** [comment]
@remibm it should now work for the 3 images. Could you confirm?

**Pull request merged**
